# Generated by Django 4.0.5 on 2022-07-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_customuser_bonus_coin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bonus_coin',
            field=models.IntegerField(default=0),
        ),
    ]
