# Generated by Django 4.0.5 on 2022-07-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_compound_gallery_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Compound',
        ),
    ]
