# Generated by Django 4.0.5 on 2022-07-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productimage_delete_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
